name: Radar Automatico

on:
  schedule:
    # Este código significa: "A cada 30 minutos, todos os dias, todas as horas"
    - cron: '*/30 * * * *'
  workflow_dispatch: # Mantém isto para poderes clicar no botão de correr manualmente

jobs:
  atualizar-dados:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Aceder aos ficheiros
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Correr Radar de Noticias
        run: |
          python radar.py
         
      - name: Guardar Mapa
        run: |
          git config --global user.name "Radar Bot"
          git config --global user.email "bot@radar.local"
          git commit -m "Atualizacao de noticias" || echo "Sem mudanças"
          git push
